<a href="https://colab.research.google.com/github/AmrMomtaz/Face-Recognition/blob/main/Face_Recognition.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Face-Recognition

##Installation and handling data

In this section we will install the required dependencies and import the data and split it as required

In [ ]:
# Clonning the data
! mkdir ~/.kaggle
! cp kaggle.json ~/.kaggle/
! kaggle datasets download -d kasikrit/att-database-of-faces
! unzip /content/att-database-of-faces.zip
! rm /content/att-database-of-faces.zip

# Importing libraries
import numpy as np
import PIL

  0% 0.00/3.61M [00:00<?, ?B/s]
100% 3.61M/3.61M [00:00<00:00, 121MB/s]


In [34]:
list_of_vectors = list()
for subject in range(1,41):
  vectors = list()
  for image in range(1,11):
    an_image = PIL.Image.open(f'/content/s{subject}/{image}.pgm')
    image_sequence = an_image.getdata()
    image_array = np.array(image_sequence).reshape((-1,1))
    vectors.append(image_array)
  list_of_vectors.append(vectors)
print(np.stack(list_of_vectors,axis = 0).reshape((40,10,-1))[0])

[[48 49 45 ... 47 46 46]
 [60 60 62 ... 32 34 34]
 [39 44 53 ... 29 26 29]
 ...
 [44 43 32 ... 43 43 37]
 [42 41 44 ... 42 43 41]
 [34 34 33 ... 37 40 33]]
